services:
  api:
    tty: true
    build: .
    command: go run main.go
    environment:
      - DATABASE_URL=mongodb://db:27017
      - PORT=8080
      - YAHOO_FINANCE_API_KEY=nFTRr5SlMs1t1SAoX3vy88PvwuohGnyVaXoKU3ll
    ports:
      - "8080:8080"
    volumes:
      - .:/go

  db:
    image: mongo:6.0.5
    ports:
      - "27017:27017"